name: second file
on: 
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: check disk space
      run: df -h 

    - name: checkout github main branch 
      uses: actions/checkout@v2

    - name: setup sdk
      uses: actions/setup-java@v1
      with: 
          java-version: 1.8

    - name: build maven pkg
      run: echo "mvn -B package --file pom.xml"

    - name: 
